

BB BBBBBBBBBBBBBBBBBB 
BBB BBBBBB B BBBBBBBBBBBBBBBBBB
BBBB
BBB BBBBBB B BBBBBBBBBBBBB
BBBBB

XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
      BBB BBB BB BBBBBBB
          XXXXXX XXXXXXFXXXXXX XXXXXXXXXXXX
      BBBBBB
    XXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        BB BBBBBBBB BB BBBBBBBB
          BB BBBBBBBBBBBBBB
            XXXXXX XXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXX XX XXXXXXXXXXXXX
          BBBB BBBBBBBBBBBBBBBBB
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXX XX XXXXXXXXXXXXX
          BBBB BBBBBBBBBBB BBB BBBBBBBBBBBBBBBBB
            XX XXXXXXXXXXXX XXXX XXXXXXXXXX
          BBBB BBBBBBBBBBB BBB BBBBBBBBBB BBB BBBBBBBBBB
            XX XXXXXXFX XXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX
          BBBBB
        BBBBB
      XXXXX
  XXXXX
  XXXXX
XXXXXX
