B BB BBBBBBB BB BBBBBBBBBBBB
XXXX XXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XX
  XXXXXXX
XXXXXX
B BBBBB
