XXXXXXXXX
XXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX

    XXX X XXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX X X
    XXX X XX XXX
        XXX XX XXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXX X XXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX

    XXXXXXXXXXXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXX

    X XXXX XXX XXXXXXXXXX 
    X XXX XXX XXXXXXXXXX 
    X XXX XXX XXXXXXXXXX 
    X XXX XXX XXXXXXXXXX 
    X XXX XXX XXXXXXXXXX
XXXXXXXXXX

    XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX

    XXXXX XXXXX
        XXX XXXXXXXXXXXXXX XXXXXX
            XXXXXXXXX X XXXX
            XXXXXXXXX X XXXX
            XXXXXXXXXX X XXXX

        XXX XXXXXXXXXXXX XXXXXX
            XX XXXX XX XXXXXXXXXX
                XXXXXX

            XXXX XXXX X XXXXXXXXXX
                XX XXXXXXXXX XX XXXXX
                    XXXXXXXXX X XXXXXXXXXX
            XXXXX
                XXXXXXXXXXXXXXXXXXXXXX
            XXXXX
                XX XXXXXXXXXX XX XXXXX
                    XXXXXXXXXX X XXXXXXXXXX
                XXXXX
                    XXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX

    X X XXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX
    XXXXX X



XXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXX

    XXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXX XXXXXXX
    XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXX

XXXXXXXX

    XXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXX

XXXX
XXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX

    XXXXXX XXXX
    X X XXX XX XX XX XXXXX XXXXX XXXXX
    X X X XXXXXXXXXX
    X X XXXXXXXXXXXX XXXXXXXXX
    X X XXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXXXX XXXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
    XXXXX XX X XX X
    XXXXX XX X XX X
    XXXXX XX X XX X
    XXXXX XX X XX X

XXXXXX

    X X XXX XX XX XX XXXXX XXXX XXXXX XX 
    X X XXX XX XX XX XXXXX XXXX XXXXX XX 
    X X XXX XX XX XX XXXXX XXXX XXXXX 
    X X XXX XX XX XX XXXXX XXXXX


