XXXXXXXXXX
XXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX

    XXXXXX XXXXXXXXXXXXXXXXXXXX
    X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XX

    XXXXXXXXXXXX XXXX  XXXXX
    XXXXXX XXXX XXXXX
    XXXXXX XXXXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX XXXXX
